# configs/Dutch_translated.yaml

dataset:
  name: "Dutch_QA"
  language: "nl"
  train_path: "data/Dutch/raw/QA_nl_train_translated.csv"
  val_path: "data/Dutch/raw/QA_nl_val_translated.csv"
  test_path: "data/Dutch/raw/QA_nl_test_translated.csv"
  cleaned_train_path: "data/Dutch/cleaned/QA_nl_train_translated_cleaned.csv"
  cleaned_val_path: "data/Dutch/cleaned/QA_nl_val_translated_cleaned.csv"
  cleaned_test_path: "data/Dutch/cleaned/QA_nl_test_translated_cleaned.csv"
  original: False

training_dir:
  logs_dir: outputs/logs/nl_translated/

parameters:
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 32
    learning_rate: 6.222044910358993e-05
    weight_decay: 0.044407922835217106
    num_train_epochs: 4
    
    