# configs/Bulgarian_original.yaml

dataset:
  name: "Cinexio"
  language: "bg"
  train_path: "data/Bulgarian/cinexio_bg_train_final_translated.csv"
  val_path: "data/Bulgarian/cinexio_bg_val_final_translated.csv"
  test_path: "data/Bulgarian/cinexio_bg_test_final_translated.csv"
  nlp_path: "data/Bulgarian/stopwords-bg.json"
  text_col: "Comment"
  label_col: "Category"
  cols_to_drop: ["ID", "Cinexio_URL", "User_Rating", "Date", "translated_text"]
  classes: [0, 1, 2]
  original: True

training:
  logs_dir: outputs/logs/bg_original/

model:
  base_model: "AIaLT-IICT/bert_bg_lit_web_base_uncased"