# configs/Chinese_original.yaml

dataset:
  name: "Weibo-Senti-100k"
  language: "ch"
  train_path: "data/Chinese/weibo_ch_train_translated.csv"
  val_path: "data/Chinese/weibo_ch_val.csv_translated.csv"
  test_path: "data/Chinese/weibo_ch_test_translated.csv"
  text_col: "review"
  label_col: "label"
  cols_to_drop: ["translated_text"]
  original: True
  classes: False

training:
  logs_dir: outputs/logs/ch_original/

model: 
  base_model: "google-bert/bert-base-chinese"