# configs/Dutch_translated.yaml

dataset:
  name: "DBRD"
  language: "nl"
  train_path: "data/Dutch/DBRD_nl_train_translated.csv"
  val_path: "data/Dutch/DBRD_nl_val_translated.csv"
  test_path: "data/Dutch/DBRD_nl_test_translated.csv"
  text_col: "translated_text"
  label_col: "label"
  cols_to_drop: ["text"]
  classes: False
  original: False

training:
  logs_dir: outputs/logs/nl_translated/
  learning_rate: 4.4585149514232965e-06
  batch_size: 8
  epochs: 3
  weight_decay: 0.015460503013261163