# configs/Chinese_original.yaml

dataset:
  name: "UD_Chinese-GSD"
  language: "ch"
  train_path_annotated: "data/Chinese/annotated/POS_ch_train_translated_annotated.csv"
  val_path_annotated: "data/Chinese/annotated/POS_ch_val_translated_annotated.csv"
  test_path_annotated: "data/Chinese/annotated/POS_ch_test_translated_annotated.csv"
  original: True

training:
  logs_dir: outputs/logs/ch_original/
  learning_rate: 5.607205497285367e-06
  batch_size: 32
  epochs: 3
  weight_decay: 0.060368204577785065

model:
  base_model: "google-bert/bert-base-chinese"