# configs/Chinese_translated.yaml

dataset:
  name: "Chinese_HSD"
  language: "ch"
  text_column: "translated_TEXT"
  label_column: "label"
  cols_to_drop: ["split", "topic", "Unnamed: 0", "TEXT", "fine-grained-label"]
  train_path: "data/Chinese/raw/HSD_ch_train_translated.csv"
  val_path: "data/Chinese/raw/HSD_ch_val_translated.csv"
  test_path: "data/Chinese/raw/HSD_ch_test_translated.csv"
  output_path_train: "data/Chinese/cleaned/HSD_ch_train_translated_cleaned.csv"
  output_path_val: "data/Chinese/cleaned/HSD_ch_val_translated_cleaned.csv"
  output_path_test: "data/Chinese/cleaned/HSD_ch_test_translated_cleaned.csv"
  original: False

training:
  batch_size: 32
  learning_rate: 2.80996641958893e-06
  weight_decay: 0.06573350483841006
  epochs: 3
  logs_dir: outputs/logs/ch_translated/
