# configs/Dutch_translated.yaml

dataset:
  name: "Dutch_HSD"
  language: "nl"
  text_column: "translated_test_case"
  label_column: "label_gold"
  cols_to_drop: ["test_case"]
  train_path: "data/Dutch/raw/HSD_nl_train_translated.csv"
  val_path: "data/Dutch/raw/HSD_nl_val_translated.csv"
  test_path: "data/Dutch/raw/HSD_nl_test_translated.csv"
  output_path_train: "data/Dutch/cleaned/HSD_nl_train_translated_cleaned.csv"
  output_path_val: "data/Dutch/cleaned/HSD_nl_val_translated_cleaned.csv"
  output_path_test: "data/Dutch/cleaned/HSD_nl_test_translated_cleaned.csv"
  original: False

training:
  batch_size: 8
  learning_rate:   2.6603342410423036e-06
  weight_decay: 0.05000146507839025
  epochs: 4
  logs_dir: outputs/logs/nl_translated/
