# configs/Russian_translated.yaml

dataset:
  name: "Russian_HSD"
  language: "ru"
  text_column: "translated_text"
  label_column: "hate_speech"
  cols_to_drop: ["Unnamed: 0", "index", "sentiment", "text"]
  train_path: "data/Russian/raw/HSD_ru_train_translated.csv"
  val_path: "data/Russian/raw/HSD_ru_val_translated.csv"
  test_path: "data/Russian/raw/HSD_ru_test_translated.csv"
  output_path_train: "data/Russian/cleaned/HSD_ru_train_translated_cleaned.csv"
  output_path_val: "data/Russian/cleaned/HSD_ru_val_translated_cleaned.csv"
  output_path_test: "data/Russian/cleaned/HSD_ru_test_translated_cleaned.csv"
  original: False


training:
  batch_size: 16
  learning_rate:  3.4398327123954815e-06
  weight_decay:  0.07742751137358556
  epochs: 4
  logs_dir: outputs/logs/ru_translated/