# configs/Dutch_translated.yaml

dataset:
  name: "SICK-NL"
  language: "nl"
  train_path: "data/Dutch/translated/NLI_nl_train_translated.csv"
  val_path: "data/Dutch/translated/NLI_nl_val_translated.csv"
  test_path: "data/Dutch/translated/NLI_nl_test_translated.csv"
  original: False
  premise_col: "translated_sentence_A"
  hypothesis_col: "translated_sentence_B"
  num_labels: 3
  label_col: "label"
  classes: [0, 1, 2]
  cols_to_drop: ["Unnamed: 0", "pair_ID", "sentence_A", "sentence_B", "relatedness_score",
                          "entailment_AB", "entailment_BA", "sentence_A_original", "sentence_B_original",
                          "sentence_A_dataset", "sentence_B_dataset", "SemEval_set", "label_seq2seq"]
                  

training:
  logs_dir: outputs/logs/nl_translated/
  learning_rate: 4.542400971751368e-06
  batch_size: 16
  epochs: 4
  weight_decay: 0.05309409301544687